/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.27
 * Generated at: 2020-01-11 13:57:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/C:/Users/ysh/spring-project-book/javachip/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/javachip/WEB-INF/lib/spring-security-taglibs-5.2.1.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1572863398000L));
    _jspx_dependants.put("jar:file:/C:/Users/ysh/spring-project-book/javachip/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/javachip/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/Users/ysh/spring-project-book/javachip/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/javachip/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1573496324614L));
    _jspx_dependants.put("/WEB-INF/views/include/header.jsp", Long.valueOf(1578750955398L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-5.2.1.RELEASE.jar", Long.valueOf(1577080989740L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  <meta name=\"description\" content=\"\">\r\n");
      out.write("  <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("  <title>JavaChip</title>\r\n");
      out.write("\r\n");
      out.write("  <!-- Font Awesome Icons -->\r\n");
      out.write("  <link href=\"/resources/vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Google Fonts -->\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700\" rel=\"stylesheet\">\r\n");
      out.write("  <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic' rel='stylesheet' type='text/css'>\r\n");
      out.write("\r\n");
      out.write("  <!-- Plugin CSS -->\r\n");
      out.write("  <link href=\"/resources/vendor/magnific-popup/magnific-popup.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Theme CSS - Includes Bootstrap -->\r\n");
      out.write("  <link href=\"/resources/css/creative.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body id=\"page-top\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Navigation -->\r\n");
      out.write("  <nav class=\"navbar navbar-expand-lg navbar-light fixed-top py-3\" id=\"mainNav\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <a class=\"navbar-brand js-scroll-trigger\" href=\"#page-top\">JavaChip</a>\r\n");
      out.write("      <button class=\"navbar-toggler navbar-toggler-right\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarResponsive\" aria-controls=\"navbarResponsive\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("        <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("      </button>\r\n");
      out.write("      <div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
      out.write("        <ul class=\"navbar-nav ml-auto my-2 my-lg-0\">\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link js-scroll-trigger\" href=\"#Test\">문제 출제</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link js-scroll-trigger\" href=\"#signup\">로그인</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link js-scroll-trigger\" href=\"#nav1\">nav1</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link js-scroll-trigger\" href=\"#nav2\">nav2</a>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("  <!-- Masthead -->\n");
      out.write("  <header class=\"masthead\">\n");
      out.write("    <div class=\"container h-100\">\n");
      out.write("      <div class=\"row h-100 align-items-center justify-content-center text-center\">\n");
      out.write("        <div class=\"col-lg-10 align-self-end\">\n");
      out.write("          <h1 class=\"text-uppercase text-white font-weight-bold\">Your Favorite Source of Free Bootstrap Themes</h1>\n");
      out.write("          <hr class=\"divider my-4\">\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-lg-8 align-self-baseline\">\n");
      out.write("          <p class=\"text-white-75 font-weight-light mb-5\">Start Bootstrap can help you build better websites using the Bootstrap framework! Just download a theme and start customizing, no strings attached!</p>\n");
      out.write("          <a class=\"btn btn-primary btn-xl js-scroll-trigger\" href=\"#about\">Find Out More</a>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </header>\n");
      out.write("\n");
      out.write("  <!-- About Section -->\n");
      out.write("  <section class=\"page-section bg-primary\" id=\"about\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("      <div class=\"row justify-content-center\">\n");
      out.write("        <div class=\"col-lg-8 text-center\">\n");
      out.write("          <h2 class=\"text-white mt-0\">We've got what you need!</h2>\n");
      out.write("          <hr class=\"divider light my-4\">\n");
      out.write("          <p class=\"text-white-50 mb-4\">Start Bootstrap has everything you need to get your new website up and running in no time! Choose one of our open source, free to download, and easy to use themes! No strings attached!</p>\n");
      out.write("          <a class=\"btn btn-light btn-xl js-scroll-trigger\" href=\"#services\">Get Started!</a>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </section>\n");
      out.write("\n");
      out.write("  <!-- Services Section -->\n");
      out.write("  <section class=\"page-section\" id=\"services\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("      <h2 class=\"text-center mt-0\">At Your Service</h2>\n");
      out.write("      <hr class=\"divider my-4\">\n");
      out.write("      <div class=\"row\">\n");
      out.write("        <div class=\"col-lg-3 col-md-6 text-center\">\n");
      out.write("          <div class=\"mt-5\">\n");
      out.write("            <i class=\"fas fa-4x fa-gem text-primary mb-4\"></i>\n");
      out.write("            <h3 class=\"h4 mb-2\">Sturdy Themes</h3>\n");
      out.write("            <p class=\"text-muted mb-0\">Our themes are updated regularly to keep them bug free!</p>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-lg-3 col-md-6 text-center\">\n");
      out.write("          <div class=\"mt-5\">\n");
      out.write("            <i class=\"fas fa-4x fa-laptop-code text-primary mb-4\"></i>\n");
      out.write("            <h3 class=\"h4 mb-2\">Up to Date</h3>\n");
      out.write("            <p class=\"text-muted mb-0\">All dependencies are kept current to keep things fresh.</p>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-lg-3 col-md-6 text-center\">\n");
      out.write("          <div class=\"mt-5\">\n");
      out.write("            <i class=\"fas fa-4x fa-globe text-primary mb-4\"></i>\n");
      out.write("            <h3 class=\"h4 mb-2\">Ready to Publish</h3>\n");
      out.write("            <p class=\"text-muted mb-0\">You can use this design as is, or you can make changes!</p>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-lg-3 col-md-6 text-center\">\n");
      out.write("          <div class=\"mt-5\">\n");
      out.write("            <i class=\"fas fa-4x fa-heart text-primary mb-4\"></i>\n");
      out.write("            <h3 class=\"h4 mb-2\">Made with Love</h3>\n");
      out.write("            <p class=\"text-muted mb-0\">Is it really open source if it's not made with love?</p>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </section>\n");
      out.write("\n");
      out.write("  <!-- Portfolio Section -->\n");
      out.write("  <section id=\"portfolio\">\n");
      out.write("    <div class=\"container-fluid p-0\">\n");
      out.write("      <div class=\"row no-gutters\">\n");
      out.write("        <div class=\"col-lg-4 col-sm-6\">\n");
      out.write("          <a class=\"portfolio-box\" href=\"/resources/img/portfolio/fullsize/1.jpg\">\n");
      out.write("            <img class=\"img-fluid\" src=\"/resources/img/portfolio/thumbnails/1.jpg\" alt=\"\">\n");
      out.write("            <div class=\"portfolio-box-caption\">\n");
      out.write("              <div class=\"project-category text-white-50\">\n");
      out.write("                Category\n");
      out.write("              </div>\n");
      out.write("              <div class=\"project-name\">\n");
      out.write("                Project Name\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-lg-4 col-sm-6\">\n");
      out.write("          <a class=\"portfolio-box\" href=\"/resources/img/portfolio/fullsize/2.jpg\">\n");
      out.write("            <img class=\"img-fluid\" src=\"/resources/img/portfolio/thumbnails/2.jpg\" alt=\"\">\n");
      out.write("            <div class=\"portfolio-box-caption\">\n");
      out.write("              <div class=\"project-category text-white-50\">\n");
      out.write("                Category\n");
      out.write("              </div>\n");
      out.write("              <div class=\"project-name\">\n");
      out.write("                Project Name\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-lg-4 col-sm-6\">\n");
      out.write("          <a class=\"portfolio-box\" href=\"/resources/img/portfolio/fullsize/3.jpg\">\n");
      out.write("            <img class=\"img-fluid\" src=\"/resources/img/portfolio/thumbnails/3.jpg\" alt=\"\">\n");
      out.write("            <div class=\"portfolio-box-caption\">\n");
      out.write("              <div class=\"project-category text-white-50\">\n");
      out.write("                Category\n");
      out.write("              </div>\n");
      out.write("              <div class=\"project-name\">\n");
      out.write("                Project Name\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-lg-4 col-sm-6\">\n");
      out.write("          <a class=\"portfolio-box\" href=\"/resources/img/portfolio/fullsize/4.jpg\">\n");
      out.write("            <img class=\"img-fluid\" src=\"/resources/img/portfolio/thumbnails/4.jpg\" alt=\"\">\n");
      out.write("            <div class=\"portfolio-box-caption\">\n");
      out.write("              <div class=\"project-category text-white-50\">\n");
      out.write("                Category\n");
      out.write("              </div>\n");
      out.write("              <div class=\"project-name\">\n");
      out.write("                Project Name\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-lg-4 col-sm-6\">\n");
      out.write("          <a class=\"portfolio-box\" href=\"/resources/img/portfolio/fullsize/5.jpg\">\n");
      out.write("            <img class=\"img-fluid\" src=\"/resources/img/portfolio/thumbnails/5.jpg\" alt=\"\">\n");
      out.write("            <div class=\"portfolio-box-caption\">\n");
      out.write("              <div class=\"project-category text-white-50\">\n");
      out.write("                Category\n");
      out.write("              </div>\n");
      out.write("              <div class=\"project-name\">\n");
      out.write("                Project Name\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-lg-4 col-sm-6\">\n");
      out.write("          <a class=\"portfolio-box\" href=\"/resources/img/portfolio/fullsize/6.jpg\">\n");
      out.write("            <img class=\"img-fluid\" src=\"/resources/img/portfolio/thumbnails/6.jpg\" alt=\"\">\n");
      out.write("            <div class=\"portfolio-box-caption p-3\">\n");
      out.write("              <div class=\"project-category text-white-50\">\n");
      out.write("                Category\n");
      out.write("              </div>\n");
      out.write("              <div class=\"project-name\">\n");
      out.write("                Project Name\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </a>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </section>\n");
      out.write("\n");
      out.write("  <!-- Call to Action Section -->\n");
      out.write("  <section class=\"page-section bg-dark text-white\">\n");
      out.write("    <div class=\"container text-center\">\n");
      out.write("      <h2 class=\"mb-4\">Free Download at Start Bootstrap!</h2>\n");
      out.write("      <a class=\"btn btn-light btn-xl\" href=\"https://startbootstrap.com/themes/creative/\">Download Now!</a>\n");
      out.write("    </div>\n");
      out.write("  </section>\n");
      out.write("\n");
      out.write("  <!-- Contact Section -->\n");
      out.write("  <section class=\"page-section\" id=\"contact\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("      <div class=\"row justify-content-center\">\n");
      out.write("        <div class=\"col-lg-8 text-center\">\n");
      out.write("          <h2 class=\"mt-0\">Let's Get In Touch!</h2>\n");
      out.write("          <hr class=\"divider my-4\">\n");
      out.write("          <p class=\"text-muted mb-5\">Ready to start your next project with us? Give us a call or send us an email and we will get back to you as soon as possible!</p>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"row\">\n");
      out.write("        <div class=\"col-lg-4 ml-auto text-center mb-5 mb-lg-0\">\n");
      out.write("          <i class=\"fas fa-phone fa-3x mb-3 text-muted\"></i>\n");
      out.write("          <div>+1 (202) 555-0149</div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-lg-4 mr-auto text-center\">\n");
      out.write("          <i class=\"fas fa-envelope fa-3x mb-3 text-muted\"></i>\n");
      out.write("          <!-- Make sure to change the email address in anchor text AND the link below! -->\n");
      out.write("          <a class=\"d-block\" href=\"mailto:contact@yourwebsite.com\">contact@yourwebsite.com</a>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </section>\n");
      out.write("\n");
      out.write("  <!-- Footer -->\n");
      out.write("  <footer class=\"bg-light py-5\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("      <div class=\"small text-center text-muted\">Copyright &copy; 2019 - Start Bootstrap</div>\n");
      out.write("    </div>\n");
      out.write("  </footer>\n");
      out.write("\n");
      out.write("  <!-- Bootstrap core JavaScript -->\n");
      out.write("  <script src=\"/resources/vendor/jquery/jquery.min.js\"></script>\n");
      out.write("  <script src=\"/resources/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("\n");
      out.write("  <!-- Plugin JavaScript -->\n");
      out.write("  <script src=\"/resources/vendor/jquery-easing/jquery.easing.min.js\"></script>\n");
      out.write("  <script src=\"/resources/vendor/magnific-popup/jquery.magnific-popup.min.js\"></script>\n");
      out.write("\n");
      out.write("  <!-- Custom scripts for this template -->\n");
      out.write("  <script src=\"/resources/js/creative.min.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
