## ddl

create sequence seq_board;

create table tbl_board (

    bno number(10,0),
    title varchar2(200) not null,
    content varchar(2000) not null,
    writer varchar2(50) not null,
    regdate date default sysdate,
    updatedate date default sysdate

);

alter table tbl_board add constraint pk_board
primary key (bno)
;


## dummy data

insert into tbl_board ( bno, title, content, writer)
values (seq_board.nextval, '테스트 제목', '테스트내용', 'user00')